### ISSUE TITLE
Remove links to picture credits without href

### ISSUE THREAD

**Issue by alfredodev** [codurance/site#1309]
On the blog posts if you add credits to the picture without providing an href, the site shows a link and it shouldn't

Example without href:
```
image:
    src: /assets/custom/img/blog/too-many-cooks.jpg
    attribution:
        text: by Adi Bolboaca
```

Example with href:
```
image:
    src: https://lh3.googleusercontent.com/-CpaZuRHtCXY/U58OGzKqovI/AAAAAAAAAKo/gkjqtS04ins/w2008-h1334-no/2014.06.13_-_socrates_uk.0083.2048.jpg
    attribution:
        text: by Antoine Vernois
        href: https://plus.google.com/photos/113819754152966550582/albums/6025548269865042577/6025550336421962482
```

You can see a working example with the error at: 
https://codurance.com/2014/11/09/too-many-cooks/

![image](https://user-images.githubusercontent.com/6770932/57624689-c3abc500-7592-11e9-848e-2b9f604f8c17.png)
